name: Docker Image

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./backend/autron

    steps:
      - uses: actions/checkout@v4

      - name: Build and Up the container
        run: docker compose up -d --build
