"""
Django settings for autron project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_random_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["164.92.218.9"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "autron",
    "rest_framework",
    "corsheaders",
    "drf_yasg",
    "okta_oauth2.apps.OktaOauth2Config",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "okta_oauth2.middleware.OktaMiddleware",
]

# OKTA https://pypi.org/project/django-okta-auth/
# Add the default Django authentication backend along with Okta
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",  # Default Django auth backend
    "okta_oauth2.backend.OktaBackend",  # Okta auth backend
)

OKTA_AUTH = {
    "ORG_URL": "", # Redacted
    "ISSUER": "", # Redacted
    "CLIENT_ID": "", # Redacted
    "CLIENT_SECRET": "", # Redacted
    "REDIRECT_URI": "", # Redacted
    "LOGIN_REDIRECT_URL": "/success",  # default
    "CACHE_PREFIX": "okta",  # default
    "CACHE_ALIAS": "default",  # default
    "PUBLIC_NAMED_URLS": (),  # default
    "PUBLIC_URLS": (""),  # Redacted
    "USE_USERNAME": False,  # default
}

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = "autron.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "autron.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# SSL/TLS settings
# https://docs.djangoproject.com/en/5.1/topics/security/
# Ensure Django always redirects HTTP to HTTPS
# SECURE_SSL_REDIRECT = True

# # Trust Nginx's proxy headers for SSL redirection
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# # SSL/TLS settings
# # https://docs.djangoproject.com/en/5.1/topics/security/
# # Ensure Django always redirects HTTP to HTTPS
SECURE_SSL_REDIRECT = True

# # Trust Nginx's proxy headers for SSL redirection
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# With MailTrap, a developer emailservice
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "sandbox.smtp.mailtrap.io"
EMAIL_HOST_USER = "0ff1317f46a497"
EMAIL_HOST_PASSWORD = "83044e0433d9ae"
EMAIL_PORT = 2525
EMAIL_USE_TLS = True

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
