services:
  autron:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autron
# maps the current directory to the /app directory in the container
    volumes:
      - .:/app
# local port:container port
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=prod # Change to 'dev' for development or 'prod' for production

# Nginx service for reverse proxy and SSL termination
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/ssl/certs
    depends_on:
      - autron
