# Generated by Django 5.1.1 on 2024-10-18 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResolver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='APIRequestResolver',
            fields=[
                ('requestresolver_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autron.requestresolver')),
                ('api_endpoint', models.URLField()),
            ],
            bases=('autron.requestresolver',),
        ),
        migrations.CreateModel(
            name='EmailRequestResolver',
            fields=[
                ('requestresolver_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autron.requestresolver')),
                ('email_address', models.EmailField(max_length=254)),
                ('email_subject', models.CharField(max_length=100)),
                ('email_body', models.TextField()),
            ],
            bases=('autron.requestresolver',),
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='software_images/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autron.department')),
            ],
        ),
    ]
