# Generated by Django 5.1.1 on 2024-10-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autron", "0002_software_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="software",
            name="requestmethod",
            field=models.CharField(default="No request method defined", max_length=50),
        ),
    ]
