# Generated by Django 5.1.1 on 2024-10-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("autron", "0002_request"),
        ("autron", "0003_software_requestmethod"),
    ]

    operations = []
