# Generated by Django 5.1.1 on 2024-11-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autron", "0004_merge_0002_request_0003_software_requestmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="software",
            name="servicenow_link",
            field=models.CharField(
                default="No ServiceNow request ticket link provided", max_length=500
            ),
        ),
    ]
