# Generated by Django 5.1.1 on 2024-11-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autron', '0005_software_servicenow_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='servicenow_link',
            field=models.CharField(default='https://www.google.com/search?q=No ServiceNow request ticket link provided', max_length=500),
        ),
    ]
