# Generated by Django 5.1.1 on 2024-11-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autron', '0007_alter_request_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='request',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Declined'), _negated=True), fields=('software', 'uid'), name='unique_software_uid_except_declined'),
        ),
    ]
