# Generated by Django 5.1.1 on 2024-11-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autron', '0006_alter_software_servicenow_link'),
        ('autron', '0008_alter_request_unique_together_and_more'),
    ]

    operations = [
    ]
