name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/autron

    steps:
    - uses: actions/checkout@v4

    - name: build docker image
      run: docker build -t autron .

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}

    - name: Tag docker image
      run: docker tag autron ghcr.io/autron/autron:latest

    - name: Push docker image
      run: docker push ghcr.io/autron/autron:latest
